spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
  datasource:
    username: sa
    password: Antares@1
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;